"""empty message

Revision ID: 1e700aa53c6d
Revises: e77bd9a93612
Create Date: 2020-08-23 22:33:28.232307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e700aa53c6d'
down_revision = 'e77bd9a93612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service__item_date_recvd', table_name='service__item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_service__item_date_recvd', 'service__item', ['date_recvd'], unique=False)
    # ### end Alembic commands ###
