"""empty message

Revision ID: e77bd9a93612
Revises: 
Create Date: 2020-08-23 21:02:39.860002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77bd9a93612'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('service__item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=64), nullable=True),
    sa.Column('item', sa.String(length=64), nullable=True),
    sa.Column('item_type', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('serial_num', sa.Integer(), nullable=True),
    sa.Column('req_serv', sa.String(length=64), nullable=True),
    sa.Column('date_recvd', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service__item_brand'), 'service__item', ['brand'], unique=False)
    op.create_index(op.f('ix_service__item_customer'), 'service__item', ['customer'], unique=False)
    op.create_index(op.f('ix_service__item_date_recvd'), 'service__item', ['date_recvd'], unique=False)
    op.create_index(op.f('ix_service__item_item'), 'service__item', ['item'], unique=False)
    op.create_index(op.f('ix_service__item_item_type'), 'service__item', ['item_type'], unique=False)
    op.create_index(op.f('ix_service__item_req_serv'), 'service__item', ['req_serv'], unique=False)
    op.create_index(op.f('ix_service__item_serial_num'), 'service__item', ['serial_num'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service__item_serial_num'), table_name='service__item')
    op.drop_index(op.f('ix_service__item_req_serv'), table_name='service__item')
    op.drop_index(op.f('ix_service__item_item_type'), table_name='service__item')
    op.drop_index(op.f('ix_service__item_item'), table_name='service__item')
    op.drop_index(op.f('ix_service__item_date_recvd'), table_name='service__item')
    op.drop_index(op.f('ix_service__item_customer'), table_name='service__item')
    op.drop_index(op.f('ix_service__item_brand'), table_name='service__item')
    op.drop_table('service__item')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
